version: '3'

services:
  mimir:
    image: mimirsbrunn

    volumes:
      - ${OSM_DIR}:/data/osm
      - ${ADDR_DIR}:/data/addresses
      - ${COSMOGONY_DIR}:/data/cosmogony
    environment:
      - RUST_LOG=info,hyper=warn,rs_es=warn

  es:
    image: elasticsearch:2
    ports:
      - 9200

  bragi:
    image: 'bragi'
    environment:
      - BRAGI_ES=http://es:9200
    ports:
     - 4000
